# Copyright (c) 2025-2026 Contributors to the AdsorPy project.
# SPDX-License-Identifier: MIT
"""Test the ``MoleculeViewer`` class of the ``molecule_lib`` module."""

from __future__ import annotations

from collections.abc import Callable
from typing import cast
from unittest.mock import Mock

import numpy as np
import pytest
from _pytest.monkeypatch import MonkeyPatch
from _pytest.subtests import Subtests
from hypothesis import strategies as st
from hypothesis.stateful import RuleBasedStateMachine, invariant, rule, run_state_machine_as_test
from hypothesis.strategies import SearchStrategy
from PySide6.QtWidgets import QDoubleSpinBox, QSlider
from pytestqt.qtbot import QtBot

from adsorpy.molecule_lib import MoleculeViewer


@pytest.fixture
def moleculeviewer_factory(qtbot: QtBot) -> Callable[[], MoleculeViewer]:
    """Make a ``MoleculeViewer`` instance."""

    def _create_viewer() -> MoleculeViewer:
        base_dict = {
            "atomkeys": ["B", "C", "N", "O", "F"],
            "colours": ["222222", "555555", "888888", "AAAAAA", "DDDDDD"],
            "atompos": np.array(
                [
                    [0, 0, 0],
                    [0, 0, 1],
                    [0, 1, 0],
                    [0, 1, 1],
                    [1, 0, 0],
                ],
                dtype=np.float64,
            ),
            "init_roll": 0.0,
            "init_pitch": None,
        }

        widget: MoleculeViewer = MoleculeViewer(**base_dict)
        qtbot.addWidget(widget)
        return widget

    return _create_viewer


def test_init_moleculeviewer(moleculeviewer_factory: Callable[[], MoleculeViewer]) -> None:
    """Test the ``__init__`` method of the ``MoleculeViewer`` class."""
    mol_vwr: MoleculeViewer = moleculeviewer_factory()
    molecule_count = 5
    assert len(mol_vwr.atomkeys) == molecule_count
    assert isinstance(mol_vwr.atomkeys, np.ndarray)

    assert mol_vwr.roll == 0.0
    assert mol_vwr.pitch == 0.0
    assert mol_vwr.yaw == 0.0


def test_toggle_settings(moleculeviewer_factory: Callable[[], MoleculeViewer], subtests: Subtests) -> None:
    """Test the toggling of ``_create_filter_panel`` values of the ``MoleculeViewer`` class."""
    mol_vwr: MoleculeViewer = moleculeviewer_factory()

    with subtests.test(msg="Background toggle."):
        old_bg = mol_vwr.bg_toggle.isChecked()
        mol_vwr.bg_toggle.click()
        assert mol_vwr.bg_toggle.isChecked() != old_bg
        mol_vwr.bg_toggle.click()
        assert mol_vwr.bg_toggle.isChecked() == old_bg

    with subtests.test(msg="Z filter toggle."):
        old_z_filter = mol_vwr.z_filter_enable.isChecked()
        mol_vwr.z_filter_enable.click()
        assert mol_vwr.z_filter_enable.isChecked() != old_z_filter
        mol_vwr.z_filter_enable.click()
        assert mol_vwr.z_filter_enable.isChecked() == old_z_filter

    with subtests.test(msg="Atom filter toggle."):
        molecule = "B"
        assert mol_vwr.disabled_molecules is None
        assert molecule in mol_vwr.atom_toggles
        mol_vwr.atom_toggles[molecule].click()
        assert mol_vwr.disabled_molecules == [molecule]
        mol_vwr.atom_toggles[molecule].click()
        assert mol_vwr.disabled_molecules is None

    with subtests.test(msg="Show bonds toggle."):
        assert not mol_vwr.show_bonds
        mol_vwr.bond_checkbox.click()
        assert mol_vwr.show_bonds


def test_update_value(
    moleculeviewer_factory: Callable[[], MoleculeViewer],
    monkeypatch: MonkeyPatch,
    subtests: Subtests,
) -> None:
    """Test the ``update_lattice_value`` and ``update_z_cutoff`` methods of the ``MoleculeViewer`` class."""
    mol_vwr: MoleculeViewer = moleculeviewer_factory()
    target_val = 2.0
    with subtests.test("update_lattice_value"):
        mock_draw = Mock()
        monkeypatch.setattr(mol_vwr, "draw", mock_draw)
        mol_vwr.lattice_spin.setValue(target_val)
        assert mol_vwr.lattice == target_val
        mock_draw.assert_called_once()

    with subtests.test("update_z_cutoff"):
        mock_apply_atom_filters = Mock()
        monkeypatch.setattr(mol_vwr, "apply_atom_filters", mock_apply_atom_filters)
        mol_vwr.z_filter_enable.click()
        mock_apply_atom_filters.assert_called_once()
        mol_vwr.z_spinbox.setValue(target_val)
        mock_apply_atom_filters.assert_called()
        assert mol_vwr.z_cutoff == target_val


class QtWidgetSyncMachine(RuleBasedStateMachine):
    """Stateful testing of slider and spinbox manipulation."""

    def __init__(self, viewer_instance: MoleculeViewer) -> None:
        """Initialise the stateful slider and spinbox tester."""
        super().__init__()
        # Store the real, factory-instantiated viewer
        self.viewer = viewer_instance
        # Extract the sliders and spinboxes generated by _add_slider_panel
        self.param_keys = ["roll", "pitch", "yaw", "x_offset", "y_offset"]
        self.sliders = cast(
            "list[QSlider]",
            [self.viewer.findChild(QSlider, f"slider_{name}") for name in self.param_keys],
        )
        self.spinboxes = cast(
            "list[QDoubleSpinBox]",
            [self.viewer.findChild(QDoubleSpinBox, f"box_{name}") for name in self.param_keys],
        )

    @staticmethod
    def _indices() -> SearchStrategy[int]:
        return st.integers(min_value=0, max_value=4)

    @rule(idx=_indices())
    def step_slider_up(self, idx: int) -> None:
        """Simulate a user incrementing a random slider."""
        slider = self.sliders[idx]
        if slider.value() < slider.maximum():
            slider.setValue(slider.value() + 1)

    @rule(idx=_indices())
    def step_slider_down(self, idx: int) -> None:
        """Simulate a user decrementing a random slider."""
        slider = self.sliders[idx]
        if slider.value() > slider.minimum():
            slider.setValue(slider.value() - 1)

    @rule(idx=_indices())
    def step_spinbox_up(self, idx: int) -> None:
        """Simulate clicking the 'Up' step arrow on the QDoubleSpinBox."""
        box = self.spinboxes[idx]
        # Qt's stepUp() automatically respects maximum bounds and singleStep settings
        box.stepUp()

    @rule(idx=_indices())
    def step_spinbox_down(self, idx: int) -> None:
        """Simulate clicking the 'Down' step arrow on the QDoubleSpinBox."""
        box = self.spinboxes[idx]
        box.stepDown()

    @rule(
        idx=_indices(),
        data=st.data(),
    )
    def direct_set_spinbox(self, idx: int, data: st.DataObject) -> None:
        """Simulate a user typing or stepping a raw float directly into the spinbox."""
        box = self.spinboxes[idx]
        # Keep values constrained within the specific spinbox parameters
        val = data.draw(
            st.floats(min_value=box.minimum(), max_value=box.maximum(), allow_nan=False, allow_infinity=False),
        )
        box.setValue(val)

    @invariant(check_during_init=True)
    def check_sync_invariance(self) -> None:
        """Assert that slider and spinbox values perfectly match at all times."""
        for idx in range(len(self.sliders)):
            slider_val = self.sliders[idx].value()
            box_val = self.spinboxes[idx].value()

            # Reconstruct what the slider value *should* be based on the float spinbox
            expected_slider_from_box = round(box_val * 10)

            assert slider_val == expected_slider_from_box, (
                f"De-sync detected on parameter index {idx}."
                f"Slider: {slider_val}, Spinbox: {box_val}."
                f"(Expected slider to be {expected_slider_from_box})"
            )
            assert box_val == getattr(self.viewer, self.param_keys[idx]), "Stored value must match changed value."


def test_molecule_viewer_sync_statefully(moleculeviewer_factory: Callable[[], MoleculeViewer]) -> None:
    """Test whether the spinbox and slider sync correctly."""
    viewer = moleculeviewer_factory()
    run_state_machine_as_test(lambda: QtWidgetSyncMachine(viewer))
