repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # frozen: v8.30.1
  hooks:
  - id: gitleaks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-ast
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: name-tests-test
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 254dd0011fda0cd4bbb281ff135792b157e43e1f # frozen: v0.11.17
  hooks:
  - id: uv-lock
