interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [
    "src",
]

[[modules]]
path = "adsorpy.rsa_calculator"
depends_on = []

[[modules]]
path = "adsorpy.randomsequentialadsorption"
depends_on = ["adsorpy.rsa_calculator"]

[[modules]]
path = "adsorpy.rsa_config"
depends_on = []

[[modules]]
path = "adsorpy.molecule_lib"
depends_on = []

[[modules]]
path = "adsorpy.run_simulation"
depends_on = ["adsorpy.randomsequentialadsorption", "adsorpy.molecule_lib", "adsorpy.rsa_config"]

[[modules]]
path = "adsorpy.gui"
depends_on = ["adsorpy.run_simulation", "adsorpy.molecule_lib"]

[[modules]]
path = "adsorpy.types"
depends_on = []
