[tox]
minversion = 4.53.0
envlist = py{310, 311, 312, 313, 314}, ruff, mypy
isolated_build = true

[gh-actions]
python =
    310: py310
    311: py311
    312: py312
    313: ruff, mypy, py313
    314: py314

[testenv]
setenv = PYTHONPATH = {toxinidir}
passenv = 
    CI
    GITHUB_*
    CODECOV_*
deps = -r{toxinidir}{/}requirements_dev.txt
commands = 
    pytest --basetemp={envtmpdir} --cov-report=term --junitxml=results.xml 
    codecov

[ruff]
basepython = python3.13
deps = -r{toxinidir}{/}requirements_lint.txt
commands = ruff check src

[mypy]
basepython = python3.13
deps = -r{toxinidir}{/}requirements_lint.txt
commands = mypy --strict --ignore-missing-imports --disallow-any-explicit --exclude {/}scripts{/} src
