min_version = "4.60.1"
env_list = [{ prefix = "py3", start = 10, stop = 14 }, "ruff", "mypy", "basedpyright", "tach", "slotscheck"]
isolated_build = true
recreate = true
labels = {static = ["ruff", "mypy", "basedpyright", "tach", "slotscheck"] }


# Quick reference: for all tests in clean environments, ``uvx tox run -r``
# For linting only: ``uvx tox run -m static -r``
# For a single env, such as py310: ``uvx tox run -e py310 -r``
[env_run_base]
runner = "uv-venv-lock-runner"
pass_env = [
    "CI",
    "GITHUB_*",
    "CODECOV_*",
    "QT_QPA_PLATFORM",
    "QT_XCB_GL_INTEGRATION",
]
extras = ["test"]
commands = [["pytest", "--cov=adsorpy", "--basetemp={envtmpdir}", "--cov-report=term", "--junitxml=results.xml"],
    [{ replace = "if", condition = "factor.py314", then = ["codecov"], extend = true }],
]

[env.ruff]
skip_install = true
deps = ["ruff"]
commands = [["ruff", "check", "src", "tests"]]

[env.mypy]
#skip_install = true
extras = ["lint", "test"]
commands = [["mypy", "src", "tests"],
]

[env.basedpyright]
extras = ["lint", "test"]
commands = [["basedpyright", "--venvpath", "{envdir}"]]

[env.slotscheck]
extras = ["lint", "gui-deps", "test"]
commands = [["slotscheck", "-m", "adsorpy", "-v"]]

[env.tach]
deps = ["tach"]
commands = [["tach", "check"]]
